# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
