# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_birthday_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday_utc',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
