#!/bin/sh
git --work-tree=/home/django/vilaparaiso.org --git-dir=/home/django/git.vilaparaiso.org checkout -f


cd /home/django/vilaparaiso.org
source env/bin/activate
pip install -r requirements/production.txt

