# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=200, unique=True, verbose_name='Email'),
        ),
    ]
